server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/time_tracker
    username: postgres
    password: fadeevaaa
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092 # Адрес вашего Kafka брокера
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer